### ISSUE TITLE
Comment mailer line in config/environments/development.rb

### ISSUE THREAD

**Issue by Sammidysam** [frc461/website-2013#67]
Does anybody else encounter the error below when running `rails s`?

```
=> Booting Thin
=> Rails 3.2.15 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/usr/local/share/gems/gems/railties-3.2.15/lib/rails/railtie/configuration.rb:85:in `method_missing': undefined method `action_mailer' for #<Rails::Application::Configuration:0x00000002eef2d0> (NoMethodError)
    from /home/sam/Documents/Workspace/website/config/environments/development.rb:17:in `block in <top (required)>'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/railtie/configurable.rb:24:in `class_eval'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/railtie/configurable.rb:24:in `configure'
    from /home/sam/Documents/Workspace/website/config/environments/development.rb:1:in `<top (required)>'
    from /usr/local/share/gems/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:251:in `require'
    from /usr/local/share/gems/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:251:in `block in require'
    from /usr/local/share/gems/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /usr/local/share/gems/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:251:in `require'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/engine.rb:576:in `block in <class:Engine>'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/initializable.rb:30:in `instance_exec'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/initializable.rb:30:in `run'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/initializable.rb:54:in `each'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/initializable.rb:54:in `run_initializers'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/application.rb:136:in `initialize!'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/sam/Documents/Workspace/website/config/environment.rb:5:in `<top (required)>'
    from /usr/local/share/gems/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:251:in `require'
    from /usr/local/share/gems/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:251:in `block in require'
    from /usr/local/share/gems/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /usr/local/share/gems/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:251:in `require'
    from /home/sam/Documents/Workspace/website/config.ru:3:in `block in <main>'
    from /usr/local/share/gems/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
    from /usr/local/share/gems/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
    from /home/sam/Documents/Workspace/website/config.ru:in `new'
    from /home/sam/Documents/Workspace/website/config.ru:in `<main>'
    from /usr/local/share/gems/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
    from /usr/local/share/gems/gems/rack-1.4.5/lib/rack/builder.rb:40:in `parse_file'
    from /usr/local/share/gems/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/commands/server.rb:46:in `app'
    from /usr/local/share/gems/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
    from /usr/local/share/gems/gems/rack-1.4.5/lib/rack/server.rb:254:in `start'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/commands/server.rb:70:in `start'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/commands.rb:55:in `block in <top (required)>'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/commands.rb:50:in `tap'
    from /usr/local/share/gems/gems/railties-3.2.15/lib/rails/commands.rb:50:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Commenting [this line](https://github.com/team461WBI/website/blob/master/config/environments/development.rb#L17) fixes the problem, but I am curious if anybody else encounters the same problem.  Considering that we don't use mailers, would it be fine to comment that line?  In [config/environments/production.rb](https://github.com/team461WBI/website/blob/master/config/environments/production.rb#L52) it is commented.

**Comment by rye** [comment]
Yes, I've gotten the same error for a long time now. It could have
something to do with Ruby versions, but I'm not sure.

**Comment by Sammidysam** [comment]
Brad gave approval to comment the line.  If anybody is annoyed by it, say so.
